// Generated by Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
@import TTTAttributedLabel;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIColor;

SWIFT_CLASS("_TtC12BotfolioChat12BotfolioChat")
@interface BotfolioChat : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull botMessageBackgroundColor;)
+ (UIColor * _Nonnull)botMessageBackgroundColor;
+ (void)setBotMessageBackgroundColor:(UIColor * _Nonnull)c;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull botMessageTextColor;)
+ (UIColor * _Nonnull)botMessageTextColor;
+ (void)setBotMessageTextColor:(UIColor * _Nonnull)c;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull userMessageBackgroundColor;)
+ (UIColor * _Nonnull)userMessageBackgroundColor;
+ (void)setUserMessageBackgroundColor:(UIColor * _Nonnull)c;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull userMessageTextColor;)
+ (UIColor * _Nonnull)userMessageTextColor;
+ (void)setUserMessageTextColor:(UIColor * _Nonnull)c;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull mainTintColor;)
+ (UIColor * _Nonnull)mainTintColor;
+ (void)setMainTintColor:(UIColor * _Nonnull)c;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull fontRegularName;)
+ (NSString * _Nonnull)fontRegularName;
+ (void)setFontRegularName:(NSString * _Nonnull)fontName;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull fontBoldName;)
+ (NSString * _Nonnull)fontBoldName;
+ (void)setFontBoldName:(NSString * _Nonnull)fontName;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull fontSemiBoldName;)
+ (NSString * _Nonnull)fontSemiBoldName;
+ (void)setFontSemiBoldName:(NSString * _Nonnull)fontName;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull placeholderImageName;)
+ (NSString * _Nonnull)placeholderImageName;
+ (void)setPlaceholderImageName:(NSString * _Nonnull)imageName;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull botfolioChatNewMessageNotification;)
+ (NSNotificationName _Nonnull)botfolioChatNewMessageNotification;
+ (void)configureWithBotApiToken:(NSString * _Nonnull)botApiToken;
+ (void)configureWithBotApiToken:(NSString * _Null_unspecified)botApiToken firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName externalJsonData:(NSDictionary<NSString *, id> * _Nullable)externalJsonData domain:(NSString * _Nonnull)domain;
+ (void)getUnreadCountWithCompletion:(void (^ _Nonnull)(NSInteger))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UIView;
@class UITableViewCell;
@class UICollectionView;
@class UICollectionViewLayout;
@class UICollectionViewCell;
@class UIImagePickerController;
@class TTTAttributedLabel;
@class UIScrollView;
@class UIGestureRecognizer;
@class UITouch;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC12BotfolioChat26BotfolioChatViewController")
@interface BotfolioChatViewController : UIViewController <UIGestureRecognizerDelegate, UITableViewDelegate, UITableViewDataSource, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, TTTAttributedLabelDelegate, UIScrollViewDelegate>
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
/**
  //////////////////////////////////////
  MARK: TableView Delegate
  //////////////////////////////////////
*/
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
/**
  /////////////////////////
  MARK: CollectionView Delegate
  /////////////////////////
*/
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
/**
  /////////////////////////
  MARK: ImagePicker Delegate
  /////////////////////////
*/
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *, id> * _Nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
/**
  /////////////////////////
  MARK: Menu
  /////////////////////////
*/
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
/**
  /////////////////////////
  MARK: TTTAttributedLabel Delegate
  /////////////////////////
*/
- (void)attributedLabel:(TTTAttributedLabel * _Null_unspecified)label didSelectLinkWithURL:(NSURL * _Null_unspecified)url;
/**
  /////////////////////////
  MARK: ScrollView Delegate
  /////////////////////////
*/
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
/**
  /////////////////////////
  MARK: GestureRecognizer Delegate
  /////////////////////////
*/
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ButtonTypes) {
  ButtonTypesWeb = 1,
  ButtonTypesPayload = 2,
  ButtonTypesPhone = 3,
};

@class CLLocation;

SWIFT_CLASS("_TtC12BotfolioChat7Message")
@interface Message : NSObject
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSDate * _Null_unspecified messageDate;
@property (nonatomic, copy) NSArray<Message *> * _Null_unspecified genericList;
@property (nonatomic, copy) NSString * _Null_unspecified imageUrl;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable addressTitle;
@property (nonatomic, copy) NSString * _Nullable addressDetails;
@property (nonatomic, strong) CLLocation * _Null_unspecified mapLocation;
@property (nonatomic, copy) NSString * _Null_unspecified videoUrl;
@property (nonatomic, copy) NSString * _Null_unspecified voiceUrl;
@property (nonatomic, copy) NSString * _Null_unspecified contactName;
@property (nonatomic, copy) NSString * _Null_unspecified contactSurname;
@property (nonatomic, copy) NSString * _Null_unspecified contactNumber;
@property (nonatomic, copy) NSString * _Null_unspecified documentName;
@property (nonatomic, copy) NSString * _Null_unspecified documentUrl;
@property (nonatomic, copy) NSString * _Null_unspecified documentType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, MessageTypes) {
  MessageTypesText = 1,
  MessageTypesButtonList = 2,
  MessageTypesGeneric = 3,
  MessageTypesGenericArray = 4,
  MessageTypesImage = 5,
  MessageTypesLocation = 6,
  MessageTypesVideo = 7,
  MessageTypesVoice = 8,
  MessageTypesContact = 9,
  MessageTypesDocument = 10,
  MessageTypesTyping = 97,
  MessageTypesNone = 98,
  MessageTypesUnread = 99,
};


@interface NSMutableData (SWIFT_EXTENSION(BotfolioChat))
@end


@interface UITableView (SWIFT_EXTENSION(BotfolioChat))
@end


@interface UIViewController (SWIFT_EXTENSION(BotfolioChat))
@end

#pragma clang diagnostic pop
